apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: image-build-and-promote
spec:
  tasks:
{{- range $index, $image := .Values.images }}
    - name: build-image-{{ $index }}
      params:
        - name: image
          value: "{{ $image.repository }}:latest"
      taskSpec:
        params:
          - name: image
            type: string
        steps:
          - name: build-image
            image: alpine
            script: |
              #!/bin/sh
              echo "Building image: $(params.image)"
              # Add your image build logic here
{{- end }}
{{- range $index, $image := .Values.images }}
{{- if $image.promotable }}
    - name: promote-image-{{ $index }}
      params:
        - name: image-to-promote
          value: "{{ $image.repository }}:latest"
      runAfter:
        - build-image-{{ $index }}
      taskSpec:
        params:
          - name: image-to-promote
            type: string
        steps:
          - name: promote-image
            image: alpine
            script: |
              #!/bin/sh
              echo "Promoting image: $(params.image-to-promote)"
              # Add your image promotion logic here
{{- end }}
{{- end }}