images:
  - repository: 'ghcr.io/fluxcd/helm-controller'
    internalRepository: 'my-docker.io/fluxcd/helm-controller'
    tag: "1.1.0"
    promotable: false
  - repository: 'ghcr.io/fluxcd/image-automation-controller'
    internalRepository: 'my-docker.io/fluxcd/image-automation-controller'
    tag: "0.1.0"
    promotable: true
  - repository: 'ghcr.io/fluxcd/source-controller'
    internalRepository: 'my-docker.io/fluxcd/source-controller'
    tag: "0.1.0"
    promotable: true